### ISSUE TITLE
Error when render_error of active_record with accepts_nested_attributes_for

### ISSUE THREAD

**Issue by phamhoaivu911** [Thinkei/google_json_response#20]
```
class Men < ActiveRecord::Base
  has_many :wives
  accepts_nested_attributes_for :wives
end

class Wife < ActiveRecord::Base
  validates :name, presence: true
end

men = Men.new(name: 'Dang', wives_attributes: [{ age: 18}])

men.valid?

men.errors.messages # {:"wives.name"=>["can't be blank"]}
men.errors.details # {"wives.name"=>[{:error=>:blank}]}

GoogleJsonResponse.render_error(men.errors) 
# NoMethodError Exception: undefined method `size' for nil:NilClass
```
Because the key in `men.errors.messages` is symbol but the key in `men.errors.details` is string, this line raises error `undef method size of nil`
https://github.com/Thinkei/google_json_response/blob/e26ef1af094c53011a505683031dd839bc1a44c6/lib/google_json_response/error_parsers/parse_active_record_error.rb#L58

**Comment by dangnm** [comment]
very nice. thanks @phamhoaivu911 . I'll take care of this issue

**Comment by dangnm** [comment]
https://github.com/Thinkei/google_json_response/pull/21
